#ifndef SMARTBODYPATHCONSTS_H
#define SMARTBODYPATHCONSTS_H

#define EMBER_SMARTBODY_NAMEPREFIX "SB"
#define EMBER_SMARTBODY_MEDIAPATH "."
#define EMBER_SMARTBODY_ASSETS_SKELETONS "."
#define EMBER_SMARTBODY_ASSETS_LOCOMOTION "."
#define EMBER_SMARTBODY_MAP_EXTENSION ".map"

#endif